### ISSUE TITLE
`preauthorized` is a field on a tailnet key, not a device key

### ISSUE THREAD

**Issue by lincolnmantracer** [tailscale/terraform-provider-tailscale#111]
This provider currently provides access to `preauthorized` on device keys. From the docs:

```
resource "tailscale_device_key" "example_key" {
  device_id           = data.tailscale_device.example_device.id
  preauthorized       = true
  key_expiry_disabled = true
}
```

However, according to the (current) tailscale docs, that's a property on a [tailnet key](https://github.com/tailscale/tailscale/blob/main/api.md#post-apiv2tailnettailnetkeys---create-a-new-key-for-a-tailnet), not a device key.

That's an understandable mistake, since the tailscale api docs were incorrect until recently. They've now been updated: https://github.com/tailscale/tailscale/issues/4571

**Comment by davidsbond** [comment]
Hey @lincolnmantracer, thanks for raising this. I believe the change will first be required in the client repository. I'll take a look at this over the weekend unless someone else beats me to it.

**Comment by davidsbond** [comment]
Hey @lincolnmantracer, I've made the change to move the field from the device key to the tailnet key. Please try out v0.11.0 and let me know if you have any further issues.

Once again thanks for raising! I can't always keep up with the API docs so it's really useful to get contributions from folks such as yourself.

**Comment by lincolnmantracer** [comment]
Will do, thanks so much for the quick fix!
