### ISSUE TITLE
Rename 'master' branch to 'main'

### ISSUE THREAD

**Issue by mayakacz** [tailscale/terraform-provider-tailscale#140]
Rename primary branch from 'master' to 'main'.
Instructions: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch
This requires an admin for this repo to change.

**Comment by davidsbond** [comment]
On top of this, the CI workflow also refers to the `master` branch directly, so will also need updating:

https://github.com/tailscale/terraform-provider-tailscale/blob/master/.github/workflows/ci.yml#L9
