### ISSUE TITLE
Update go.mod before new release

### ISSUE THREAD

**Issue by stack72** [tailscale/terraform-provider-tailscale#141]
Hi 

In order to make sure we (Pulumi) can still continue to use the library, please can you update the go.mod to reflect the new namespace of tailscale (https://github.com/tailscale/terraform-provider-tailscale/blob/master/go.mod#L1)

This won't affect your binary but will help us be able to ingest the library easily

Paul

**Comment by DentonGentry** [comment]
We understand that we need to do so when we're ready to make a release.

**Comment by stack72** [comment]
Thanks so much @DentonGentry :)
