### ISSUE TITLE
json: cannot unmarshal array into Go struct field ACLEntry.acls.proto of │ type string

### ISSUE THREAD

**Issue by lapkritinis** [tailscale/terraform-provider-tailscale#155]
**Describe the bug**
Snippet from ACL:
```
    {
      "action": "accept",
      "ports": [
        "public_aza:5432",
        "public_azb:5432",
        "public_azc:5432",
        "private_aza:443",
        "private_azb:443",
        "private_azc:443",
        "database_aza:5432",
        "database_azb:5432",
        "database_azc:5432"
      ],
      "users": [
        "group:developers"
      ],
      "src": ["*"],
      "dst": ["*"],
      "proto": ["tcp"]
    },
```

Having "proto" gives error:
json: cannot unmarshal array into Go struct field ACLEntry.acls.proto of
│ type string

**To Reproduce**
Steps to reproduce the behaviour:
Apply ACL with proto as above.

**Expected behaviour**
Apply ACL as described in JSON

**Desktop (please complete the following information):**
 - OS: terraform cloud (amd_linux I believe)
 - Terraform Version 1.2.28
 - Provider Version 0.13.5

**Additional context**
I see that provider is applying "something" which wasnt written in ACL and I wanted to add these to ACL. Here is output from provider if src dst and proto are missing:

```
  ~ resource "tailscale_acl" "access_controls" {
      ~ acl = jsonencode(
          ~ {
              ~ acls          = [
                  ~ {
                      - dst    = null -> null
                      - proto  = "" -> null
                      - src    = null -> null
                        # (3 unchanged elements hidden)
                    }
```
...... not providing full output...

**Comment by davidsbond** [comment]
Hey @lapkritinis, based on the [ACL docs](https://tailscale.com/kb/1018/acls/#acl-rules) The `src` and `dst` fields in an ACL rule should be arrays rather than a strings:

```
{
  "action": "accept",
  "src": [ list-of-sources... ],
  "proto": "protocol", // optional
  "dst": [ list-of-destinations... ],
}
```

**Comment by lapkritinis** [comment]
Hey @davidsbond yes, you are correct. I did performed tests one by one with src, dst - its good. But it fails on `"proto": ["tcp"]`. I also updated by bug report.

**Comment by lapkritinis** [comment]
Closing as mistakenly reported.
