### ISSUE TITLE
allowing validating the ACL tests before `terraform apply`

### ISSUE THREAD

**Issue by codekitchen** [tailscale/terraform-provider-tailscale#158]
We prefer to manage our infrastructure with Terraform whenever possible. But one nice feature that [Tailscale's GitOps Pusher](https://github.com/tailscale/tailscale/tree/main/cmd/gitops-pusher) supports is to validate your ACL logic pre-merge in a PR by asking Tailscale to run the ACL tests. It'd be great if the Terraform provider could support this somehow as well.

I'm not entirely sure how to best fit this into a Terraform workflow -- my first thought would be to have `terraform plan` run the validation step. But that would perhaps be surprising to some?

**Comment by davidsbond** [comment]
One approach for this could be to modify the existing ACl validation to send if off to the Tailscale API for the test endpoint.

https://github.com/tailscale/terraform-provider-tailscale/blob/8a21ee62d44618946609d42667e9925746ac826a/tailscale/resource_acl.go#L38

The client package would also need a method added to call the testing endpoint.
