### ISSUE TITLE
Terraform Tailscale 0.13.5 does not have arm64 release

### ISSUE THREAD

**Issue by anhdle14** [tailscale/terraform-provider-tailscale#168]
**Describe the bug**

```bash
$ terraform init
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/davidsbond/tailscale v0.13.5 does not have a package available for your current platform, darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms supported.
```

**To Reproduce**

Terraform init with tailscale provider

**Expected behaviour**

Init successfully

**Desktop (please complete the following information):**
 - OS: Mac Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64
 - Terraform Version 1.3
 - Provider Version 0.13.5

**Additional context**

**Comment by steenzout** [comment]
> **Describe the bug**
> 
> ```shell
> $ terraform init
> │ Error: Incompatible provider version
> │ 
> │ Provider registry.terraform.io/davidsbond/tailscale v0.13.5 does not have a package available for your current platform, darwin_arm64.
> │ 
> │ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms supported.
> ```
> 
> **To Reproduce**
> 
> Terraform init with tailscale provider
> 
> **Expected behaviour**
> 
> Init successfully
> 
> **Desktop (please complete the following information):**
> 
>     * OS: Mac Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64
> 
>     * Terraform Version 1.3
> 
>     * Provider Version 0.13.5
> 
> 
> **Additional context** Add any other context about the problem here.

the `source` is different now. `davidsbond` => `tailscale`.

this works for me:

```terraform
terraform {
  required_providers {
    tailscale = {
      source  = "tailscale/tailscale"
      version = "0.13.5"
    }
  }
}
```

**Comment by anhdle14** [comment]
@steenzout hmm I double check the `required_providers`. And for me it is:

```tf
    tailscale = {
      source  = "tailscale/tailscale"
      version = "~> 0.13.5"
    }
```

**Comment by anhdle14** [comment]
Tried with a blank terraform module without any problem, just not sure what happened with the previous one when I do the migration. Will close this because it is a client-side problem. 

```
terraform {
  required_providers {
    tailscale = {
      source  = "tailscale/tailscale"
    }
  }
}

provider "tailscale" {}
```

**Comment by anhdle14** [comment]
`terraform -chdir=<path> state replace-provider davidsbond/tailscale tailscale/tailscale` does the trick for me.
