### ISSUE TITLE
Datasource "tailscale_device" - False Negative - Error: Could not find device with name

### ISSUE THREAD

**Issue by MarcusAtCrexi** [tailscale/terraform-provider-tailscale#172]
**Describe the bug**

This morning one of our engineers reported that the Tailscale provider is throwing an error stating that it cannot find a device which was previously detected: `Error: Could not find device with name`.

Terraform apply was working fine until this morning, although it may have been a few days since we last applied.

```
terraform {
  required_version = "1.2.4"
  required_providers {
    tailscale = {
      source  = "tailscale/tailscale"
      version = ">= 0.13.5"
    }
  }
}

provider "tailscale" {
  # Configuration options
  api_key = "<removed>"
  tailnet = "mytailnet"
}

data "tailscale_device" "vpn-gateway" {
  name = "aws-vpn"
}
```

Error:

```
│ Error: Could not find device with name aws-vpn
│ 
│   with data.tailscale_device.vpn-gateway,
│   on data.tf line 5, in data "tailscale_device" "vpn-gateway":
│    5: data "tailscale_device" "vpn-gateway" {
│ 
```

**To Reproduce**

1. Run Terraform apply with the above, replacing API keys and such as needed.

2. Observe the error mentioned above:  `Error: Could not find device with name aws-vpn`

3. Check in your Tailnet for this machine by the exact name specified in TF. This should indicate that the machine should have been successfully identified/located via the data source.

It's unclear if this is a provider issue or a Tailscale API issue, but I'm raising it here anyways.

**Expected behavior**

My expectation is that Terraform and the provider should correctly locate the machine in the Tailnet.

**Desktop (please complete the following information):**
 - OS: MacOS Monterey = 12.4
 - Terraform Version       = 1.2.4
 - Provider Version          = 0.13.5

**Additional context**

For posterity, it's worth mentioning that there are no differences in machine name casing between the machine name in Terraform and Tailscale.

Thanks for taking a look into this :)

**Comment by DentonGentry** [comment]
The error message comes from: https://github.com/tailscale/terraform-provider-tailscale/blob/44e79d58f94b9de67b53b0707e81bb759a4b4a46/tailscale/data_source_device.go#L85
The root cause is almost certainly in something coming back from the API.

There are a couple ways to proceed:
- The API the terraform provider is using is a tailnet GET: https://github.com/tailscale/tailscale/blob/main/api.md#tailnet-devices-get. If you have an API key available and could run the curl command linked there to check if `aws-vpn` appears.
- from the information in this bug report, we don't know what tailnet you're referring to (and would prefer not to put information about a tailnet into public bugs). [Contacting Tailscale support](https://tailscale.com/contact/support/) would let them look up the tailnet state.

**Comment by MarcusAtCrexi** [comment]
> The error message comes from:
> 
> https://github.com/tailscale/terraform-provider-tailscale/blob/44e79d58f94b9de67b53b0707e81bb759a4b4a46/tailscale/data_source_device.go#L85
> 
> The root cause is almost certainly in something coming back from the API.
> 
> There are a couple ways to proceed:
> 
>     * The API the terraform provider is using is a tailnet GET: https://github.com/tailscale/tailscale/blob/main/api.md#tailnet-devices-get. If you have an API key available and could run the curl command linked there to check if `aws-vpn` appears.
> 
>     * From the information in this bug report, we don't know what tailnet you're referring to (and would prefer not to put information about a tailnet into public bugs). [Contacting Tailscale support](https://tailscale.com/contact/support/) would let them look up the tailnet state.

Thank for pointing out the GET request. It looks like they've changed the name of our machine to something that doesn't reflect our Tailnet domain.

Instead of say, `aws-vpn.mydomain.com` that was used previously, the `name` parameter returns `aws-vpn.tail<redact>.ts.net`.

Our Terraform apply is now successfully locating the device by the new name. Thanks again.

**Comment by davidsbond** [comment]
I had this problem with my homelab, your device names have likely changed as a result of magic DNS becoming generally available. 

> If you’re already using MagicDNS, your tailnet has been automatically assigned a new tailnet name of the form tail<hex>.ts.net, in addition to the existing name

I had to make a change like so:

https://github.com/davidsbond/homad/commit/0b843bd6635000a2f59c371fad0231e6e52b0922#diff-7517e717a22eb2827989930d6736adc76cb1ab96ea185818d4681c7c538f5e52R2

**Comment by MarcusAtCrexi** [comment]
> I had this problem with my homelab, your device names have likely changed as a result of MagicDNS becoming generally available.
> 
> > If you’re already using MagicDNS, your tailnet has been automatically assigned a new tailnet name of the form tail.ts.net, in addition to the existing name
> 
> I had to make a change like so:
> 
> [davidsbond/homad@0b843bd#diff-7517e717a22eb2827989930d6736adc76cb1ab96ea185818d4681c7c538f5e52R2](https://github.com/davidsbond/homad/commit/0b843bd6635000a2f59c371fad0231e6e52b0922#diff-7517e717a22eb2827989930d6736adc76cb1ab96ea185818d4681c7c538f5e52R2)

Oh I see, that makes sense. Glad to hear the change will persist. Thank you.

**Comment by ceedubs** [comment]
I lost several hours to this when `terraform apply` stopped working with no changes on our end, so here are my findings in hopes that they prevent someone else from spending too long on the same issue:

As @davidsbond pointed out, if you previously had a `tailscale_device` with a `name` like `mydevice.myorganization.com` that now needs to look like `mydevice.tailfe8c.ts.net`.

**However,** the `tailnet` argument that is passed into the `provider "tailscale"` is still the [organization name](https://tailscale.com/kb/1217/tailnet-name/#organization-name) (_not_ the tailnet name). This argument seems to be used to generate the API URLs and those seem to require org names, not tailnet names.

We had been passing the same variable into both `tailnet = var.tailnet` and `name = "mydevice.${var.tailnet}"`, so it didn't work with _either_ the org name or the tailnet name. Now we have separate variables to track the two.

I love Tailscale, but I do think that there are a number of things that could have helped prevent issues for people. Some thoughts that come to mind:

- Does the `name` field on `tailscale_device` really need to be fully qualified with the tailnet name?
  - This isn't how the name shows up in the `Machines` UI, so it is a real head scratcher when it can't find the device.
  - Isn't this predetermined by the tailnet/org, which is already passed into the tailscale provider?
- For existing devices on existing tailnets that never had MagicDNS enabled, did the device names really need to change without warning?
- The API docs show `/:tailnet/` in the REST endpoints. Should those accept a tailnet (and fall back to an org name for compatibility)?

**Comment by OJFord** [comment]
@DentonGentry I think this should be re-opened, per @ccedubs description above the 'Magic DNS' name is what's required, not the 'organization' as on the provider? There's no way of getting this name (no data source, no output on the `tailscale_dns_preferences` where Magic DNS is enabled) short of adding a second variable.

And what's required there if Magic DNS _isn't_ enabled then? 🤔
