### ISSUE TITLE
Support for nodeAttrs

### ISSUE THREAD

**Issue by petrilli** [tailscale/terraform-provider-tailscale#179]
**Describe the bug**

The provider doesn't currently seem to support the `nodeAttrs` attribute of the ACL in the `tailscale_acl` resource. 

**To Reproduce**
Steps to reproduce the behaviour:

1. Add an `nodeAttr` attribute to the ACL in Terraform resource file:
```hcl
nodeAttrs : [
  {
    target = ["tag:funnelable"]
    attr   = ["funnel"]
  }
]
```
2. Run a `terraform plan`
3. Receive error

Error received:

> Error: invalid ACL [...] json: unknown field "nodeAttrs". (This error may be caused by a new ACL feature that is not yet supported by this terraform provider.

**Expected behaviour**

JSON is rendered and the ACL is updated.

**Desktop (please complete the following information):**
 - OS: n/a
 - Terraform Version: 0.13.5
 - Provider Version: 1.2.8

**Additional context**

Enrolled in the alpha Funnel feature.

**Comment by knyar** [comment]
I've updated the API client library in #185 so you should now be able to set `nodeAttr`

**Comment by petrilli** [comment]
That's awesome! Any idea when the new provider will be packaged and released?

**Comment by knyar** [comment]
@petrilli v0.13.6 has been released.

**Comment by petrilli** [comment]
Thanks! You all are awesome.
