### ISSUE TITLE
Please add an option to retrieve tailscale_devices (Data Source) via regexp

### ISSUE THREAD

**Issue by gitbensons** [tailscale/terraform-provider-tailscale#202]
**Is your feature request related to a problem? Please describe.**
I want to add tags on tailscale devices based on their name. Unfortunately the data source `tailscale_devices` only has the option to match by name prefix. Our devices would be identified by the suffix.

**Describe the solution you'd like**
Add more flexible option to match tailscale devices via `tailscale_devices` data source.

**Additional context**
Will add a PR to add `name_regexp` as the most flexible way to identify devices.

**Comment by knyar** [comment]
As suggested in #203, this does not require adding new arguments to the data resource.
