### ISSUE TITLE
Tailscale provider returns 403 when user tailnet does not match

### ISSUE THREAD

**Issue by heretic098** [tailscale/terraform-provider-tailscale#206]
One of the more common (I suspect) issues a new user of the provider may run into is that the tailnet name may not be correct. In this case the provider will return an error like this:

```
│ Error: Failed to create key
│
│   with module.my_module.tailscale_tailnet_key.default,
│   on ../modules/gcp_gitlab_runner/[main.tf](http://main.tf/) line 28, in resource "tailscale_tailnet_key" "default":
│   28: resource "tailscale_tailnet_key" "default" {
│
│ user tailnet does not match (403)
╵
```
I encountered this issue on the free tier and was able to resolve it by referring to the [API documentation](https://github.com/tailscale/tailscale/blob/main/api.md#tailnet). My tailnet name was the same as my organization name, i.e. equivalent to "example.com" in the API documentation. I'm not immediately sure how the tailnet name changes when you start paying for tailscale as the API docs are not all that clear.

I think that README.md could be updated to make this a little clearer.

**Comment by OJFord** [comment]
Yes, I assumed it was supposed to be the 'tailnet name' under DNS:
![image](https://user-images.githubusercontent.com/3946014/223225216-95461736-506f-4c02-8850-04253a0ff2f0.png)

but it's actually meant to be the value of 'organization' under Settings:
![image](https://user-images.githubusercontent.com/3946014/223225304-e57a8e83-5e2b-47be-803b-834789b63372.png)

**Comment by dnapier** [comment]
Was also just caught by this. Glad to see this issue. Changing to organization name resolved my issue.

**Comment by tom10271** [comment]
Are you kidding me?
