### ISSUE TITLE
Key expiry differs in terraform state and in web UI

### ISSUE THREAD

**Issue by gberenice** [tailscale/terraform-provider-tailscale#236]
**Describe the bug**
We're managing pre-authentication keys via Terraform, and here is the example  of the resource:
```
resource "tailscale_tailnet_key" "default" {
    ephemeral     = false
    expiry        = 7776000 # 90 days in seconds
    id            = "XX"
    key           = (sensitive value)
    preauthorized = true
    reusable      = true
    tags          = [
        "tag:dev-tailscale-subnet-router",
    ]
}
```
However, in the console, there is no expiration date for the key:
<img width="372" alt="Screenshot 2023-05-12 at 12 27 49" src="https://github.com/tailscale/terraform-provider-tailscale/assets/30597968/2b63bd41-ad26-47c8-8420-880646d1be6f">

The key behaves like it actually expires, here is an example of the error we had before:
```bash
│ Error: Failed to fetch key
│ 
│   with module.tailscale_subnet_router.tailscale_tailnet_key.default,
│   on .terraform/modules/tailscale_subnet_router/main.tf line 36, in resource "tailscale_tailnet_key" "default":
│   36: resource "tailscale_tailnet_key" "default" {
│ 
│ 404 page not found (404)
```

But the subnet router that used the key from the example above still was connected to the Tailnet, and all was operational.

**To Reproduce**
1. Create a `tailscale_tailnet_key` resource by applying Terraform configuration.
2. Start Tailscale subnet router with the key. Command that we use:
    ```bash
     sudo tailscale up --advertise-routes=${routes} --authkey=${authkey} --hostname=${hostname}
     ```
4. Compare Terraform state and web console UI information about key expiration.

**Expected behaviour**
The key expiration date in web console corresponds to the one set in the`tailscale_tailnet_key` resource.

**Desktop (please complete the following information):**
 - OS: macOS
 - Terraform Version: 1.3.2
 - Provider Version: 0.13.7

**Comment by DentonGentry** [comment]
An [authkey](https://tailscale.com/kb/1085/auth-keys/) can be used to authorize a new node to join the tailnet. Authkeys created [using the Web UI](https://login.tailscale.com/admin/settings/keys) have a lifetime of 90 days by default. After 90 days, the authkey will not be able to authorize a new node to join the tailnet.

Once a new node has been authorized, it generates a machine key and node key which allow it to connect Wireguard tunnels to other devices. The machine key and node key are not tied to the authkey which created this node. The authkey can expire or be revoked, and nodes which it previously created are unaffected. The authkey expiration only impacts its ability to create new nodes.

Node keys by default expire after 6 months. However, nodes created with tags are almost always servers and it was an unwelcome default to have servers expire six months after creation. So nodes created with tags have their node keys set to never expire by default.

**Comment by gberenice** [comment]
@DentonGentry ah, so the "Key expiry" I see in the web console is for node key, not auth key, correct? Then it all makes sense. Thanks a lot for the detailed answer!

**Comment by DentonGentry** [comment]
> so the "Key expiry" I see in the web console is for node key, not auth key, correct?

Yes.
