### ISSUE TITLE
tailscale_tailnet_key: requested tags are invalid or not permitted

### ISSUE THREAD

**Issue by aviau** [tailscale/terraform-provider-tailscale#247]
**Describe the bug**

I hope this is a bug and not something that I don't understand, but this used to work with this exact terraform config...

I am getting `requested tags [tag:prod] are invalid or not permitted (400)` on `terraform apply`, trying to create a new `tailscale_tailnet_key` with the `tag:prod` tag.

I tried to rule out an ACL issue by changing the tagowners to all kinds of things, including an empty list, and no dice.

I am creating the key like so:
```hcl
resource "tailscale_tailnet_key" "key" {
  reusable      = true
  preauthorized = true
  expiry        = 60 * 60 * 24 * 90
  tags          = ["tag:prod"]
}
```

The ACL looks like this:
```hcl
resource "tailscale_acl" "acl" {
  acl = jsonencode({

    tagOwners : {
      "tag:corp" : ["autogroup:admin"],
      "tag:prod" : ["autogroup:admin"],
      "tag:staging" : ["autogroup:admin"],
    }

    acls : [
      {
        // All employees can access their own devices
        action = "accept"
        src    = ["autogroup:members"]
        dst    = ["autogroup:self:*"]
      },
      {
        // Access company-wide services.
        action = "accept"
        src    = ["autogroup:members"]
        dst    = ["tag:corp:*"]
      },
      {
        // Access prod and staging services.
        action = "accept"
        src = [
          "autogroup:members",
        ]
        dst = ["tag:staging:*", "tag:prod:*"],
      },
    ],

  })
}
```

My provider uses the oauth client with the `all` scope, so it shouldn't be related to it not being allowed certain API calls.
```hcl
provider "tailscale" {
  tailnet             = "censored"
  oauth_client_id     = "censored"
  oauth_client_secret = "censored"
  scopes              = ["all"]
}
```

Note that I am on the starter plan. (if this is a plan issue, please improve your error messages...)

**Comment by aviau** [comment]
After more testing, I managed to generate the key by using my personal API key instead.

So, it looks like the bug is the following: domain-level-admin oauth-generated keys can't create auth keys for tags they don't own.

**Comment by willnorris** [comment]
oh... you have `tags = ["tags:prod"]` in your tailscale_tailnet_key config.  That should probably be `tag:prod`.  Typo in this bug or is that actually what you have in your config?

**Comment by aviau** [comment]
> Typo in this bug or is that actually what you have in your config?

It was a typo in this bug. I'll edit it for clarity.

**Comment by aviau** [comment]
See the tailscale issue for the full story.

My understanding is that there is nothing to fix in the terraform provider for now.

**Comment by OJFord** [comment]
Just in case it helps anyone else: I had the same, because the tag didn't already exist. It's not implicitly created, and there also doesn't seem to be a way to create/manage tags through the provider currently.

So: create the tag in admin console (without a user owner, per above); then `tailscale_tailnet_key` will be able to use it.
