### ISSUE TITLE
Not able to retrieve the device

### ISSUE THREAD

**Issue by jjsaunier** [tailscale/terraform-provider-tailscale#327]
I'm currently migrating some infra of dev workspace org using the tailscale terraform version `0.13.13` but I'm facing this issue

```
╷
│ Error: Could not find device with name dev-workspace-nat
│
│   with data.tailscale_device.dev_workspace_nat,
│   on dev-workspace.tf line 50, in data "tailscale_device" "dev_workspace_nat":
│   50: data "tailscale_device" "dev_workspace_nat" {
│
```

I'm unable to retrieve the device whereas it's correctly registered.

<img width="405" alt="image" src="https://github.com/tailscale/terraform-provider-tailscale/assets/1763341/565c6b72-b7b0-40f7-9c9d-fd2345fdaa60">

I'm retrieving the device via 

```
data "tailscale_device" "dev_workspace_nat" {
    name = "dev-workspace-nat"
    wait_for = "60s"
}
```

Am I missing something or doing something wrong? I have followed the logic on the terraform doc https://registry.terraform.io/providers/tailscale/tailscale/latest/docs/resources/device_key 

I'm interested to get your feedback, this is ruining my plans 😅

**Comment by knyar** [comment]
First step would probably be to use the same credentials you're passing to the Tailscale terraform provider to issue an [list devices](https://github.com/tailscale/tailscale/blob/main/api.md#list-tailnet-devices) API call manually and check that you see the node there.

**Comment by jjsaunier** [comment]
Thanks for your insight

I can retrieve the machine however the name is the one I expected. 

I got `"name": "dev-workspace-nat.tail6efba.ts.net"` 

If I understand correctly, I should contact my machine name with `.tail6efba.ts.net` to get back on the actual name?

**Comment by knyar** [comment]
Yeah, it seems that the `name` should be an FQDN, just like the name [in the example](https://registry.terraform.io/providers/tailscale/tailscale/latest/docs/data-sources/device#example-usage) is.

**Comment by jjsaunier** [comment]
Yes, got it working thanks

To be honest the example is not super clear, in fact you know only if you know and make sense after you re read it. May be a little description like: name is formatted like `<device-name>.<tailscale-domain>` make it clearer 

Anyway, thanks for your answers!
