### ISSUE TITLE
Submit GPG key for OpenTofu Registry

### ISSUE THREAD

**Issue by Gowiem** [tailscale/terraform-provider-tailscale#335]
**Is your feature request related to a problem? Please describe.**
Yes, when using OpenTofu. 

**Describe the solution you'd like**

* When using the terraform provider via `tofu`, you get the following warning when it's installed (see screenshot as well): 

> Installed tailscale/tailscale v0.13.13. Signature validation was skipped due to the registry not containing GPG keys for this provider

* It would be great to see this get addressed. To do so, please do the following: "Submit new Provider Signing Key" from opentofu/registry's [Issues page](https://github.com/opentofu/registry/issues/new/choose). [Here is a recent example](https://github.com/opentofu/registry/issues/206). 

![CleanShot 2024-02-19 at 12 17 50](https://github.com/tailscale/terraform-provider-tailscale/assets/1392040/7f64f652-00ec-473f-953a-f3068b38e3a4)

**Additional context**
* [See a related issue here](https://github.com/carlpett/terraform-provider-sops/issues/115) and corresponding [registry PR](https://github.com/opentofu/registry/issues/233)

**Comment by mpminardi** [comment]
Thank you for flagging this! Have opened https://github.com/opentofu/registry/issues/729 in the registry,

**Comment by mpminardi** [comment]
The change has been merged in the registry and it is looking like signature validation is now happening:

![image](https://github.com/user-attachments/assets/6dae29be-5be2-4b6b-88ea-e942551542e8)

Going to be closing this as a result.
