### ISSUE TITLE
New resource: tailscale_tailnet_settings

### ISSUE THREAD

**Issue by reegnz** [tailscale/terraform-provider-tailscale#425]
**Is your feature request related to a problem? Please describe.**

I want to manage my tailnet settings with terraform.

**Describe the solution you'd like**
Please expose the [tailnet_settings API](https://tailscale.com/api#tag/tailnetsettings/GET/tailnet/{tailnet}/settings) through the terraform provider.

**Additional context**
I'm willing to contribute a PR if the project is open to merging outside PR-s.

**Comment by mpminardi** [comment]
Hey @reegnz ! We implemented this in https://github.com/tailscale/terraform-provider-tailscale/pull/415 but have not yet released a provider version that includes this new resource. Release date for an updated version of the provider is still TBD at this point.

**Comment by mpminardi** [comment]
Hey @reegnz ! We've just released v0.17.0 of the provider which [has this resource](https://registry.terraform.io/providers/tailscale/tailscale/latest/docs/resources/tailnet_settings). Going to close this issue as a result!
